### ISSUE TITLE
Redux

### ISSUE THREAD

**Issue by germ13** [vutran/spa-starter-kit#1]
I am looking at your code and can't seem to find the boilerplate for Redux.

**Comment by vutran** [comment]
Hi @germ13,

I will be building out this starter kit in the future with samples on how to implement Redux. I'm currently loaded with work at the moment so I can't give an estimate on when this will be done.

However, you're more than welcome to fork the repo and submit a pull request if you'd like to give it a shot! :+1:

**Comment by germ13** [comment]
I understand...no worries.  I've got plenty of responsibilities as well. :computer: 

When I made the issue I was looking for a starter boiler-plate kind of program to get my feet wet with redux.  Im familiar with React, but was new to redux. 

In the past week, I learned quite a bit...so let me get a bit more comfortable with the subject and I will definitely write something up.

**Comment by vutran** [comment]
A simple demo has been added with the latest commit. Feel free to expand on it if you'd like.
